export const BEANS = [
  {
    id: "ethiopia",
    index: "01",
    name: "Ethiopia Yirgacheffe",
    lot: "Konga · 74110",
    notes: ["jasmine", "lemon zest", "honey"],
    roast: "Light",
    process: "Natural",
    altitude: "2,100 masl",
    price: 18,
    development: 42,
    color: "#b74c2d",
  },
  {
    id: "colombia",
    index: "02",
    name: "Colombia Huila",
    lot: "Huila · Caturra",
    notes: ["caramel", "red apple", "cocoa"],
    roast: "Medium",
    process: "Washed",
    altitude: "1,850 masl",
    price: 16,
    development: 56,
    color: "#d39a44",
  },
  {
    id: "sumatra",
    index: "03",
    name: "Sumatra Mandheling",
    lot: "Gayo · Typica",
    notes: ["dark chocolate", "cedar", "earth"],
    roast: "Dark",
    process: "Wet hulled",
    altitude: "1,500 masl",
    price: 17,
    development: 82,
    color: "#6e4936",
  },
  {
    id: "kenya",
    index: "04",
    name: "Kenya AA Nyeri",
    lot: "Nyeri · SL28",
    notes: ["blackcurrant", "tomato", "brown sugar"],
    roast: "Light",
    process: "Double washed",
    altitude: "1,900 masl",
    price: 19,
    development: 48,
    color: "#a6362b",
  },
  {
    id: "guatemala",
    index: "05",
    name: "Guatemala Antigua",
    lot: "Atitlán · Bourbon",
    notes: ["milk chocolate", "orange", "almond"],
    roast: "Medium",
    process: "Washed",
    altitude: "1,700 masl",
    price: 16,
    development: 68,
    color: "#c66b36",
  },
  {
    id: "decaf",
    index: "06",
    name: "Swiss Water Decaf Blend",
    lot: "Northwind · Night lot",
    notes: ["toffee", "hazelnut", "smooth"],
    roast: "Medium",
    process: "Swiss Water",
    altitude: "Mixed lot",
    price: 15,
    development: 64,
    color: "#9f673a",
  },
];

export const STEPS = [
  {
    n: 1,
    time: "00:00",
    title: "Weigh",
    cue: "18g / 300ml",
    body: "Use 18g of coffee for every 300ml of water. A cheap scale beats an expensive guess.",
  },
  {
    n: 2,
    time: "00:15",
    title: "Grind",
    cue: "medium-fine",
    body: "Grind just before brewing, medium-fine for pour over. Pre-ground coffee stales in minutes.",
  },
  {
    n: 3,
    time: "00:30",
    title: "Bloom",
    cue: "95°C / 30 sec",
    body: "Pour twice the coffee weight in 95°C water and wait 30 seconds for the gases to escape.",
  },
  {
    n: 4,
    time: "03:00",
    title: "Pour",
    cue: "slow circles",
    body: "Pour the remaining water in slow circles over 2.5 minutes. Total brew time: about 3 minutes.",
  },
];

export const REVIEWS = [
  {
    quote: "The Yirgacheffe changed what I thought coffee could taste like. Floral, bright, ridiculous.",
    name: "Maya T.",
    role: "Subscriber since 2022",
  },
  {
    quote: "Roasted Tuesday, at my door Thursday. Nobody else I have tried comes close on freshness.",
    name: "Daniel R.",
    role: "Home barista",
  },
  {
    quote: "I gifted the subscription to my dad and now he lectures me about bloom times. Worth it.",
    name: "Priya S.",
    role: "Gift subscriber",
  },
];

export const POLICIES = {
  "/shipping": {
    index: "01",
    title: "Shipping",
    intro: "Fresh coffee should travel quickly and predictably.",
    sections: [
      ["Dispatch", "We roast on Tuesdays and Fridays and dispatch completed orders within 24 hours of roasting."],
      ["Delivery", "Norway orders usually arrive in 2–4 working days. International delivery commonly takes 5–12 working days."],
      ["Tracking", "A tracking link is emailed when the parcel leaves Bergen. Customs charges, where applicable, are the recipient’s responsibility."],
    ],
  },
  "/returns": {
    index: "02",
    title: "Returns",
    intro: "If the batch or parcel is wrong, we will make it right.",
    sections: [
      ["Coffee", "Because roasted coffee is perishable, we cannot accept preference-based returns on opened bags."],
      ["Problems", "Contact us within 14 days if an item is damaged, incorrect, or missing. Include the order number and a photograph where useful."],
      ["Resolution", "Approved claims are replaced or refunded to the original payment method. Brewing equipment may be returned unused within 14 days."],
    ],
  },
  "/privacy": {
    index: "03",
    title: "Privacy",
    intro: "We collect the minimum information needed to roast, ship, and reply.",
    sections: [
      ["What we keep", "Order contact details, delivery information, and messages you choose to send us."],
      ["Why", "We use this information to fulfil orders, provide support, prevent fraud, and send opted-in batch notes."],
      ["Your choice", "You may request access, correction, or deletion by contacting hello@northwind.coffee. We do not sell personal data."],
    ],
  },
};
